apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: alibabacloud-credential
  namespace: kube-system
data:
  ACCESS_KEY_ID: base64 encoded access_key_id
  ACCESS_KEY_SECRET: base64 encoded access_key_secret