apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-admin
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alicloud-csi-plugin
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete", "get", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "list", "watch", "delete", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alicloud-csi-plugin
subjects:
  - kind: ServiceAccount
    name: csi-admin
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: alicloud-csi-plugin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: diskplugin.csi.alibabacloud.com
spec:
  attachRequired: true
  podInfoOnMount: true
---
  kind: DaemonSet
  apiVersion: apps/v1
  metadata:
    name: csi-plugin
    namespace: kube-system
  spec:
    selector:
      matchLabels:
        app: csi-plugin
    template:
      metadata:
        labels:
          app: csi-plugin
      spec:
        tolerations:
          - operator: Exists
        nodeSelector:
          kubernetes.io/os: linux
        serviceAccount: csi-admin
        priorityClassName: system-node-critical
        hostNetwork: true
        hostPID: true
        containers:
          - name: disk-driver-registrar
            image: registry.cn-hongkong.aliyuncs.com/acs/csi-node-driver-registrar:v2.3.0-038aeb6-aliyun
            imagePullPolicy: IfNotPresent
            args:
              - "--v=5"
              - "--csi-address=/var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock"
              - "--kubelet-registration-path=/var/lib/kubelet/csi-plugins/diskplugin.csi.alibabacloud.com/csi.sock"
            volumeMounts:
              - name: kubelet-dir
                mountPath: /var/lib/kubelet
              - name: registration-dir
                mountPath: /registration
          - name: csi-plugin
            securityContext:
              privileged: true
              capabilities:
                add: ["SYS_ADMIN"]
              allowPrivilegeEscalation: true
            image: registry.cn-hongkong.aliyuncs.com/acs/csi-plugin:v1.22.8-e84838c-aliyun
            imagePullPolicy: "IfNotPresent"
            args:
              - "--endpoint=$(CSI_ENDPOINT)"
              - "--v=2"
              - "--driver=disk"
            env:
              - name: KUBE_NODE_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.nodeName
              - name: CSI_ENDPOINT
                value: unix://var/lib/kubelet/csi-plugins/driverplugin.csi.alibabacloud.com-replace/csi.sock
              - name: MAX_VOLUMES_PERNODE
                value: "15"
              - name: SERVICE_TYPE
                value: "plugin"
              - name: ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: alibabacloud-credential
                    key: ACCESS_KEY_ID
              - name: ACCESS_KEY_SECRET
                valueFrom:
                  secretKeyRef:
                    name: alibabacloud-credential
                    key: ACCESS_KEY_SECRET
            livenessProbe:
              httpGet:
                path: /healthz
                port: healthz
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
            ports:
              - name: healthz
                containerPort: 11260
                protocol: TCP
            volumeMounts:
              - name: kubelet-dir
                mountPath: /var/lib/kubelet/
                mountPropagation: "Bidirectional"
              - name: etc
                mountPath: /host/etc
              - name: host-log
                mountPath: /var/log/
              - name: container-dir
                mountPath: /var/lib/container
                mountPropagation: "Bidirectional"
              - name: host-dev
                mountPath: /dev
                mountPropagation: "HostToContainer"
        volumes:
          - name: registration-dir
            hostPath:
              path: /var/lib/kubelet/plugins_registry
              type: DirectoryOrCreate
          - name: container-dir
            hostPath:
              path: /var/lib/container
              type: DirectoryOrCreate
          - name: kubelet-dir
            hostPath:
              path: /var/lib/kubelet
              type: Directory
          - name: host-dev
            hostPath:
              path: /dev
          - name: host-log
            hostPath:
              path: /var/log/
          - name: etc
            hostPath:
              path: /etc